CREATE TABLE IF NOT EXISTS public.mobile_push_device (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform varchar(16) NOT NULL,
    device_token varchar(512) NOT NULL,
    country_iso varchar(2) NOT NULL,
    alerts_only boolean NOT NULL DEFAULT true,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_mobile_push_device_token'
    ) THEN
        ALTER TABLE public.mobile_push_device
            ADD CONSTRAINT uk_mobile_push_device_token UNIQUE (device_token);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_mobile_push_device_country
    ON public.mobile_push_device USING btree (country_iso);

CREATE INDEX IF NOT EXISTS idx_mobile_push_device_platform
    ON public.mobile_push_device USING btree (platform);
