CREATE TABLE IF NOT EXISTS public.external_account (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider character varying(32) NOT NULL,
    external_user_id character varying(128) NOT NULL,
    email character varying(255),
    access_token_ciphertext character varying(2048),
    refresh_token_ciphertext character varying(2048),
    scopes character varying(512),
    token_expires_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    last_synced_at timestamp(6) with time zone,
    CONSTRAINT uk_external_account_provider_user UNIQUE (provider, external_user_id)
);

CREATE TABLE IF NOT EXISTS public.user_watched_anime (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_account_id bigint NOT NULL,
    anime_slug character varying(255) NOT NULL,
    watched_at timestamp(6) with time zone NOT NULL,
    source character varying(32) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_user_watched_anime_account_slug_source UNIQUE (external_account_id, anime_slug, source),
    CONSTRAINT fk_user_watched_anime_external_account
        FOREIGN KEY (external_account_id) REFERENCES public.external_account (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_external_account_email
    ON public.external_account USING btree (email);

CREATE INDEX IF NOT EXISTS idx_user_watched_anime_account
    ON public.user_watched_anime USING btree (external_account_id);

CREATE INDEX IF NOT EXISTS idx_user_watched_anime_slug
    ON public.user_watched_anime USING btree (anime_slug);
