CREATE TABLE IF NOT EXISTS public.trakt_sync_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider varchar(32) NOT NULL,
    synced_at timestamp(6) with time zone NOT NULL,
    watched_imported integer NOT NULL,
    ratings_imported integer NOT NULL,
    unmatched_count integer NOT NULL,
    CONSTRAINT chk_trakt_sync_event_counts CHECK (
        watched_imported >= 0
        AND ratings_imported >= 0
        AND unmatched_count >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_trakt_sync_event_provider
    ON public.trakt_sync_event USING btree (provider);

CREATE INDEX IF NOT EXISTS idx_trakt_sync_event_synced_at
    ON public.trakt_sync_event USING btree (synced_at);
