--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: affiliate_click_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.affiliate_click_event (
    id bigint NOT NULL,
    affiliate_link_id bigint NOT NULL,
    anime_slug character varying(180) NOT NULL,
    clicked_at timestamp(6) with time zone NOT NULL,
    country_code character varying(2) NOT NULL,
    provider_slug character varying(100) NOT NULL
);


--
-- Name: affiliate_click_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.affiliate_click_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.affiliate_click_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: affiliate_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.affiliate_link (
    id bigint NOT NULL,
    active boolean NOT NULL,
    affiliate_url text NOT NULL,
    click_count integer NOT NULL,
    country_code character varying(2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    provider_slug character varying(100) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: affiliate_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.affiliate_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.affiliate_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: anime; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anime (
    id bigint NOT NULL,
    anilist_id bigint NOT NULL,
    average_score integer,
    banner_image character varying(500),
    cover_image character varying(500),
    description text,
    description_es text,
    end_day integer,
    end_month integer,
    end_year integer,
    episodes integer,
    format character varying(20),
    popularity integer,
    primary_studio character varying(120),
    season character varying(10),
    season_year integer,
    slug character varying(255),
    start_day integer,
    start_month integer,
    start_year integer,
    status character varying(30),
    synced_at timestamp(6) with time zone,
    title_english character varying(255),
    title_romaji character varying(255),
    tmdb_id bigint
);


--
-- Name: anime_genre; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anime_genre (
    anime_id bigint NOT NULL,
    genre character varying(50) NOT NULL
);


--
-- Name: anime_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anime_tag (
    rank integer,
    anime_id bigint NOT NULL,
    tag_name character varying(120) NOT NULL
);


-- 
-- Name: anime_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.anime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: anime_override; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anime_override (
    id bigint NOT NULL,
    field_name character varying(50) NOT NULL,
    field_value text NOT NULL,
    locale character varying(5) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(50),
    anime_id bigint NOT NULL
);


--
-- Name: anime_override_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.anime_override ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anime_override_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    confirmed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    unsubscribed_at timestamp(6) with time zone
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_token (
    id bigint NOT NULL,
    country_code character varying(2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    token_type character varying(30) NOT NULL,
    used_at timestamp(6) with time zone,
    anime_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: email_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_event (
    id bigint NOT NULL,
    clicked_at timestamp(6) with time zone NOT NULL,
    source_anime_slug character varying(180) NOT NULL,
    target_anime_slug character varying(180) NOT NULL
);


--
-- Name: recommendation_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription (
    id bigint NOT NULL,
    country_code character varying(2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    notified_at timestamp(6) with time zone,
    anime_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: watch_provider; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.watch_provider (
    id bigint NOT NULL,
    anime_id bigint NOT NULL,
    country_code character varying(2) NOT NULL,
    logo_url character varying(500),
    provider_name character varying(100) NOT NULL,
    provider_type character varying(20) NOT NULL,
    tmdb_provider_id integer,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: watch_provider_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.watch_provider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_provider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: affiliate_click_event affiliate_click_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliate_click_event
    ADD CONSTRAINT affiliate_click_event_pkey PRIMARY KEY (id);


--
-- Name: affiliate_link affiliate_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliate_link
    ADD CONSTRAINT affiliate_link_pkey PRIMARY KEY (id);


--
-- Name: anime_genre anime_genre_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime_genre
    ADD CONSTRAINT anime_genre_pkey PRIMARY KEY (anime_id, genre);


--
-- Name: anime_override anime_override_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime_override
    ADD CONSTRAINT anime_override_pkey PRIMARY KEY (id);


--
-- Name: anime anime_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime
    ADD CONSTRAINT anime_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: email_token email_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_token
    ADD CONSTRAINT email_token_pkey PRIMARY KEY (id);


--
-- Name: recommendation_event recommendation_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_event
    ADD CONSTRAINT recommendation_event_pkey PRIMARY KEY (id);


--
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: affiliate_link uk_affiliate_link_provider_country; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliate_link
    ADD CONSTRAINT uk_affiliate_link_provider_country UNIQUE (provider_slug, country_code);


--
-- Name: anime_override uk_anime_override_field_locale; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime_override
    ADD CONSTRAINT uk_anime_override_field_locale UNIQUE (anime_id, field_name, locale);


--
-- Name: email_token uk_email_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_token
    ADD CONSTRAINT uk_email_token_hash UNIQUE (token_hash);


--
-- Name: subscription uk_subscription_user_anime_country; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT uk_subscription_user_anime_country UNIQUE (user_id, anime_id, country_code);


--
-- Name: watch_provider uk_watch_provider_anime_country_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watch_provider
    ADD CONSTRAINT uk_watch_provider_anime_country_name UNIQUE (anime_id, country_code, provider_name);


--
-- Name: anime ukdya227e8e0sie1hk9orw8ywgu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime
    ADD CONSTRAINT ukdya227e8e0sie1hk9orw8ywgu UNIQUE (anilist_id);


--
-- Name: anime ukrbaubl4w907xjq3fhxnl411y4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime
    ADD CONSTRAINT ukrbaubl4w907xjq3fhxnl411y4 UNIQUE (slug);


--
-- Name: watch_provider watch_provider_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watch_provider
    ADD CONSTRAINT watch_provider_pkey PRIMARY KEY (id);


--
-- Name: idx_affiliate_click_anime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_affiliate_click_anime ON public.affiliate_click_event USING btree (anime_slug);


--
-- Name: idx_affiliate_click_clicked_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_affiliate_click_clicked_at ON public.affiliate_click_event USING btree (clicked_at);


--
-- Name: idx_affiliate_click_provider_country; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_affiliate_click_provider_country ON public.affiliate_click_event USING btree (provider_slug, country_code);


--
-- Name: idx_affiliate_link_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_affiliate_link_active ON public.affiliate_link USING btree (active);


--
-- Name: idx_affiliate_link_provider_country; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_affiliate_link_provider_country ON public.affiliate_link USING btree (provider_slug, country_code);


--
-- Name: idx_anime_override_anime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_anime_override_anime ON public.anime_override USING btree (anime_id);


--
-- Name: idx_email_token_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_token_expires ON public.email_token USING btree (expires_at);


--
-- Name: idx_email_token_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_token_user ON public.email_token USING btree (user_id);


--
-- Name: idx_recommendation_event_clicked_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_event_clicked_at ON public.recommendation_event USING btree (clicked_at);


--
-- Name: idx_recommendation_event_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_event_source ON public.recommendation_event USING btree (source_anime_slug);


--
-- Name: idx_recommendation_event_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_event_target ON public.recommendation_event USING btree (target_anime_slug);


--
-- Name: idx_subscription_anime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscription_anime ON public.subscription USING btree (anime_id, country_code);


--
-- Name: idx_subscription_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subscription_user ON public.subscription USING btree (user_id);


--
-- Name: idx_watch_provider_anime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_watch_provider_anime ON public.watch_provider USING btree (anime_id);


--
-- Name: idx_watch_provider_country; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_watch_provider_country ON public.watch_provider USING btree (country_code);


--
-- Name: anime_genre fk72693b55ypxe99ik71d43od0v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime_genre
    ADD CONSTRAINT fk72693b55ypxe99ik71d43od0v FOREIGN KEY (anime_id) REFERENCES public.anime(id);


--
-- Name: anime_tag fkj4u9yd6aggva29wwxmpnxe30y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime_tag
    ADD CONSTRAINT fkj4u9yd6aggva29wwxmpnxe30y FOREIGN KEY (anime_id) REFERENCES public.anime(id);


--
-- Name: anime_override fk_anime_override_anime; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anime_override
    ADD CONSTRAINT fk_anime_override_anime FOREIGN KEY (anime_id) REFERENCES public.anime(id) ON DELETE CASCADE;


--
-- Name: email_token fk_email_token_anime; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_token
    ADD CONSTRAINT fk_email_token_anime FOREIGN KEY (anime_id) REFERENCES public.anime(id) ON DELETE CASCADE;


--
-- Name: email_token fk_email_token_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_token
    ADD CONSTRAINT fk_email_token_user FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: subscription fk_subscription_anime; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fk_subscription_anime FOREIGN KEY (anime_id) REFERENCES public.anime(id) ON DELETE CASCADE;


--
-- Name: subscription fk_subscription_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fk_subscription_user FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
