CREATE TABLE IF NOT EXISTS public.anime_embedding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_id bigint NOT NULL,
    model character varying(120) NOT NULL,
    content_hash character varying(64) NOT NULL,
    embedding text NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_anime_embedding_anime_model'
    ) THEN
        ALTER TABLE public.anime_embedding
            ADD CONSTRAINT uk_anime_embedding_anime_model UNIQUE (anime_id, model);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_anime_embedding_anime'
    ) THEN
        ALTER TABLE public.anime_embedding
            ADD CONSTRAINT fk_anime_embedding_anime
            FOREIGN KEY (anime_id)
            REFERENCES public.anime(id)
            ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_anime_embedding_model
    ON public.anime_embedding USING btree (model);

CREATE INDEX IF NOT EXISTS idx_anime_embedding_content_hash
    ON public.anime_embedding USING btree (content_hash);
