CREATE TABLE IF NOT EXISTS public.news_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(120) NOT NULL,
    type character varying(20) NOT NULL,
    url character varying(500) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    last_fetched_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_news_source_name') THEN
        ALTER TABLE public.news_source ADD CONSTRAINT uk_news_source_name UNIQUE (name);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.news_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug character varying(200) NOT NULL,
    title character varying(200) NOT NULL,
    summary character varying(500),
    body text,
    source_url character varying(800) NOT NULL,
    source_name character varying(120) NOT NULL,
    image_url character varying(800),
    original_title character varying(500),
    original_excerpt text,
    anime_id bigint,
    status character varying(20) NOT NULL,
    auto_generated boolean NOT NULL DEFAULT true,
    meta_title character varying(70),
    meta_description character varying(160),
    llm_tokens_used integer,
    published_at timestamp(6) with time zone,
    fetched_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_news_item_slug') THEN
        ALTER TABLE public.news_item ADD CONSTRAINT uk_news_item_slug UNIQUE (slug);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_news_item_source_url') THEN
        ALTER TABLE public.news_item ADD CONSTRAINT uk_news_item_source_url UNIQUE (source_url);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_news_item_anime') THEN
        ALTER TABLE public.news_item
            ADD CONSTRAINT fk_news_item_anime
            FOREIGN KEY (anime_id)
            REFERENCES public.anime(id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_news_item_status_published
    ON public.news_item USING btree (status, published_at);

CREATE INDEX IF NOT EXISTS idx_news_item_anime
    ON public.news_item USING btree (anime_id);
