CREATE TABLE IF NOT EXISTS public.admin_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(255) NOT NULL,
    totp_secret character varying(255)
);

CREATE TABLE IF NOT EXISTS public.newsletter_subscriber (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmed_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    unsubscribed_at timestamp(6) with time zone
);

CREATE TABLE IF NOT EXISTS public.newsletter_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    token_type character varying(40) NOT NULL,
    used_at timestamp(6) with time zone,
    subscriber_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.availability_change_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_id bigint NOT NULL,
    anime_slug character varying(180) NOT NULL,
    changed_at timestamp(6) with time zone NOT NULL,
    change_type character varying(10) NOT NULL,
    country_code character varying(2) NOT NULL,
    provider_name character varying(100) NOT NULL,
    provider_type character varying(20) NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_admin_user_username'
    ) THEN
        ALTER TABLE public.admin_user
            ADD CONSTRAINT uk_admin_user_username UNIQUE (username);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_newsletter_subscriber_email'
    ) THEN
        ALTER TABLE public.newsletter_subscriber
            ADD CONSTRAINT uk_newsletter_subscriber_email UNIQUE (email);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_newsletter_token_hash'
    ) THEN
        ALTER TABLE public.newsletter_token
            ADD CONSTRAINT uk_newsletter_token_hash UNIQUE (token_hash);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_newsletter_token_subscriber'
    ) THEN
        ALTER TABLE public.newsletter_token
            ADD CONSTRAINT fk_newsletter_token_subscriber
            FOREIGN KEY (subscriber_id)
            REFERENCES public.newsletter_subscriber(id)
            ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_newsletter_token_subscriber
    ON public.newsletter_token USING btree (subscriber_id);

CREATE INDEX IF NOT EXISTS idx_newsletter_token_expires
    ON public.newsletter_token USING btree (expires_at);

CREATE INDEX IF NOT EXISTS idx_availability_change_changed_at
    ON public.availability_change_event USING btree (changed_at);

CREATE INDEX IF NOT EXISTS idx_availability_change_anime
    ON public.availability_change_event USING btree (anime_slug);

CREATE INDEX IF NOT EXISTS idx_availability_change_provider_country
    ON public.availability_change_event USING btree (provider_name, country_code);
