CREATE TABLE IF NOT EXISTS public.push_subscription (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email character varying(255) NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    country_iso character varying(2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    delivery_success_count integer,
    delivery_failure_count integer,
    last_status_code integer,
    last_delivered_at timestamp(6) with time zone,
    last_failed_at timestamp(6) with time zone
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_push_subscription_endpoint'
    ) THEN
        ALTER TABLE public.push_subscription
            ADD CONSTRAINT uk_push_subscription_endpoint UNIQUE (endpoint);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_push_subscription_country
    ON public.push_subscription USING btree (country_iso);

CREATE INDEX IF NOT EXISTS idx_push_subscription_email
    ON public.push_subscription USING btree (user_email);
