CREATE TABLE IF NOT EXISTS public.anime_character (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anilist_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    image character varying(500)
);

CREATE TABLE IF NOT EXISTS public.studio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anilist_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    is_animation_studio boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public.anime_character_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_id bigint NOT NULL,
    character_id bigint NOT NULL,
    role character varying(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.anime_studio (
    anime_id bigint NOT NULL,
    studio_id bigint NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_anime_character_anilist_id'
    ) THEN
        ALTER TABLE public.anime_character
            ADD CONSTRAINT uk_anime_character_anilist_id UNIQUE (anilist_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_studio_anilist_id'
    ) THEN
        ALTER TABLE public.studio
            ADD CONSTRAINT uk_studio_anilist_id UNIQUE (anilist_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_studio_slug'
    ) THEN
        ALTER TABLE public.studio
            ADD CONSTRAINT uk_studio_slug UNIQUE (slug);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_anime_character_role'
    ) THEN
        ALTER TABLE public.anime_character_role
            ADD CONSTRAINT uk_anime_character_role UNIQUE (anime_id, character_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_anime_studio'
    ) THEN
        ALTER TABLE public.anime_studio
            ADD CONSTRAINT uk_anime_studio UNIQUE (anime_id, studio_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_anime_character_role_anime'
    ) THEN
        ALTER TABLE public.anime_character_role
            ADD CONSTRAINT fk_anime_character_role_anime
            FOREIGN KEY (anime_id)
            REFERENCES public.anime(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_anime_character_role_character'
    ) THEN
        ALTER TABLE public.anime_character_role
            ADD CONSTRAINT fk_anime_character_role_character
            FOREIGN KEY (character_id)
            REFERENCES public.anime_character(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_anime_studio_anime'
    ) THEN
        ALTER TABLE public.anime_studio
            ADD CONSTRAINT fk_anime_studio_anime
            FOREIGN KEY (anime_id)
            REFERENCES public.anime(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_anime_studio_studio'
    ) THEN
        ALTER TABLE public.anime_studio
            ADD CONSTRAINT fk_anime_studio_studio
            FOREIGN KEY (studio_id)
            REFERENCES public.studio(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_anime_character_role_anime
    ON public.anime_character_role USING btree (anime_id);

CREATE INDEX IF NOT EXISTS idx_anime_character_role_character
    ON public.anime_character_role USING btree (character_id);

CREATE INDEX IF NOT EXISTS idx_anime_studio_anime
    ON public.anime_studio USING btree (anime_id);

CREATE INDEX IF NOT EXISTS idx_anime_studio_studio
    ON public.anime_studio USING btree (studio_id);
