package com.dondeanime.backend.news;

import java.text.Normalizer;
import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@Entity
@Table(
        name = "news_item",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_news_item_slug", columnNames = "slug"),
                @UniqueConstraint(name = "uk_news_item_source_url", columnNames = "source_url"),
                @UniqueConstraint(name = "uk_news_item_dedup_key", columnNames = "dedup_key")
        },
        indexes = {
                @Index(name = "idx_news_item_status_published", columnList = "status,published_at"),
                @Index(name = "idx_news_item_anime", columnList = "anime_id")
        })
public class NewsItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    @Size(max = 200)
    @Column(nullable = false, unique = true, length = 200)
    private String slug;

    @NotBlank
    @Size(max = 200)
    @Column(nullable = false, length = 200)
    private String title;

    @Size(max = 500)
    @Column(length = 500)
    private String summary;

    @Column(columnDefinition = "TEXT")
    private String body;

    @NotBlank
    @Size(max = 800)
    @Column(name = "source_url", nullable = false, unique = true, length = 800)
    private String sourceUrl;

    @NotBlank
    @Size(max = 120)
    @Column(name = "source_name", nullable = false, length = 120)
    private String sourceName;

    @Size(max = 800)
    @Column(name = "image_url", length = 800)
    private String imageUrl;

    @Size(max = 500)
    @Column(name = "original_title", length = 500)
    private String originalTitle;

    @Column(name = "original_excerpt", columnDefinition = "TEXT")
    private String originalExcerpt;

    @Column(name = "anime_id")
    private Long animeId;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private NewsStatus status = NewsStatus.DRAFT;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = true;

    @Size(max = 70)
    @Column(name = "meta_title", length = 70)
    private String metaTitle;

    @Size(max = 160)
    @Column(name = "meta_description", length = 160)
    private String metaDescription;

    @Column(name = "llm_tokens_used")
    private Integer llmTokensUsed;

    @Column(name = "published_at")
    private Instant publishedAt;

    @Column(name = "fetched_at", nullable = false)
    private Instant fetchedAt;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Clave de deduplicación estable (URL canónica, con fallback fuente+título)
     * calculada por la librería anime-feed-parser. Es la barrera dura de
     * idempotencia: mata duplicados que difieren solo en utm_*, barra final,
     * http/https o reescrituras de feedburner que source_url no pillaba.
     */
    @Size(max = 800)
    @Column(name = "dedup_key", length = 800)
    private String dedupKey;

    /** Hash del contenido (título+excerpt normalizados); señal de edición upstream. */
    @Size(max = 64)
    @Column(name = "content_hash", length = 64)
    private String contentHash;

    public NewsItem() {
    }

    @PrePersist
    void prePersist() {
        Instant now = Instant.now();
        createdAt = now;
        updatedAt = now;
        if (fetchedAt == null) {
            fetchedAt = now;
        }
    }

    @PreUpdate
    void preUpdate() {
        updatedAt = Instant.now();
    }

    /** Slug a partir de un título, mismo criterio que el resto del proyecto. */
    public static String slugify(String value) {
        if (value == null || value.isBlank()) {
            return "";
        }
        String normalized = Normalizer.normalize(value, Normalizer.Form.NFD)
                .replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
        normalized = normalized.toLowerCase()
                .replaceAll("[^a-z0-9\\s-]", "")
                .replaceAll("\\s+", "-")
                .replaceAll("-+", "-");
        if (normalized.startsWith("-")) {
            normalized = normalized.substring(1);
        }
        if (normalized.endsWith("-")) {
            normalized = normalized.substring(0, normalized.length() - 1);
        }
        return normalized.length() > 200 ? normalized.substring(0, 200) : normalized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getSourceUrl() {
        return sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    public String getSourceName() {
        return sourceName;
    }

    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getDedupKey() {
        return dedupKey;
    }

    public void setDedupKey(String dedupKey) {
        this.dedupKey = dedupKey;
    }

    public String getContentHash() {
        return contentHash;
    }

    public void setContentHash(String contentHash) {
        this.contentHash = contentHash;
    }

    public String getOriginalTitle() {
        return originalTitle;
    }

    public void setOriginalTitle(String originalTitle) {
        this.originalTitle = originalTitle;
    }

    public String getOriginalExcerpt() {
        return originalExcerpt;
    }

    public void setOriginalExcerpt(String originalExcerpt) {
        this.originalExcerpt = originalExcerpt;
    }

    public Long getAnimeId() {
        return animeId;
    }

    public void setAnimeId(Long animeId) {
        this.animeId = animeId;
    }

    public NewsStatus getStatus() {
        return status;
    }

    public void setStatus(NewsStatus status) {
        this.status = status;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getMetaTitle() {
        return metaTitle;
    }

    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }

    public String getMetaDescription() {
        return metaDescription;
    }

    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }

    public Integer getLlmTokensUsed() {
        return llmTokensUsed;
    }

    public void setLlmTokensUsed(Integer llmTokensUsed) {
        this.llmTokensUsed = llmTokensUsed;
    }

    public Instant getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(Instant publishedAt) {
        this.publishedAt = publishedAt;
    }

    public Instant getFetchedAt() {
        return fetchedAt;
    }

    public void setFetchedAt(Instant fetchedAt) {
        this.fetchedAt = fetchedAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
